WIP

diff --git a/.github/workflows/slack-notify.yml b/.github/workflows/slack-notify.yml
--- a/.github/workflows/slack-notify.yml
+++ b/.github/workflows/slack-notify.yml
@@ -6,10 +6,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Try to fail
-        run: exit 1 # Cause the step to fail
       - name: List of the GitHub Actions environment variables
         run: env
+      - name: Try to fail
+        run: exit 1 # Cause the step to fail
       - name: Slack Notification
         if: ${{ failure() }}
         uses: rtCamp/action-slack-notify@v2
