WIP

diff --git a/.github/workflows/slack-notify.yml b/.github/workflows/slack-notify.yml
--- a/.github/workflows/slack-notify.yml
+++ b/.github/workflows/slack-notify.yml
@@ -6,11 +6,11 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: "Set ENV var"
+      - name: "Set GITHUB_ACTOR"
         run: |
           echo "GITHUB_ACTOR=$GITHUB_ACTOR" >> $GITHUB_ENV
       - name: Try to fail
-        run: exit 1 # Cause the step to fail to remove
+        run: exit 1 # Cause the step to fail
       - name: Slack Notification
         if: ${{ failure() }}
         uses: rtCamp/action-slack-notify@v2
@@ -19,4 +19,4 @@ jobs:
           SLACK_USERNAME: "CI-Checker"
           SLACK_COLOR: ${{ job.status }}
           SLACK_ICON: https://www.laboutiqueofficielle.com/favicon-114x114.png
-          SLACK_MESSAGE: "@${{ env.GITHUB_ACTOR }} your last CI just failed."
+          SLACK_MESSAGE: "${{ env.GITHUB_ACTOR }} your last CI just Failed."
