Test custom message with author

diff --git a/.github/workflows/slack-notify.yml b/.github/workflows/slack-notify.yml
--- a/.github/workflows/slack-notify.yml
+++ b/.github/workflows/slack-notify.yml
@@ -7,7 +7,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: Try to fail
-        run: exit 1
+        run: exit 1 # Cause the step to fail
       - name: Slack Notification
         if: ${{ failure() }}
         uses: rtCamp/action-slack-notify@v2
@@ -16,3 +16,4 @@ jobs:
           SLACK_USERNAME: "CI-Checker"
           SLACK_COLOR: ${{ job.status }}
           SLACK_ICON: https://www.laboutiqueofficielle.com/favicon-114x114.png
+          SLACK_MESSAGE: '${{ GITHUB_ACTOR }} :rocket:'
